### PR TITLE
Adds new absmax aggregation method

### PR DESCRIPTION
**Pull request by yadsirhc**
absmax is a new aggregation method which returns the largest
absolute value when aggregating to a lower precision archive.

Useful for data such as time offsets, where you care about retaining
the value furthest from zero when aggregating but would prefer to
preserve whether the offset was positive or negative.

### CODE REVIEW

**Comment by SEJeff** [comment]
@yadsirhc can you please rebase this to the latest changes in whisper.git master?

**Comment by yadsirhc** [comment]
@SEJeff Done.  Also updated the README to reflect avg_zero since it was the reason for the conflicts but hadn't itself been documented.

**Comment by deniszh** [comment]
@yadsirhc - could you please rebase your change if still needed?

**Comment by yadsirhc** [comment]
Rebased, as requested.

**Comment by yadsirhc** [comment]
No conflicts remain with the base branch.  Is the rebaseneeded label still appropriate?  What is preventing merge now (or back in Aug 2016, for that matter)?

**Comment by deniszh** [comment]
Hello @yadsirhc,
Sorry for very long merging time, we're trying to maintain Graphite properly now.
Will merge this today or tomorrow, no worries.
Does anyone want to review too? /cc @graphite-project/committers

**Pull request merged**
