### PR TITLE
whisper-dump.py: add --time-format option.

### PR DESCRIPTION
**Pull request by xavierog**
Hi,

This is a simple improvement for those of us who use whisper-dump AND are bad at reading Unix timestamps. Let me know about anything that can be improved.

### CODE REVIEW

**Comment by deniszh** [comment]
`whisper-dump` is quite specific tool, usually, it's needed for some metrics export cases. For human readable output, you can use `whisper-fetch`.  But in general I'm fine with this change, but please fix README too.
I'll take care of a failing test.

**Comment by deniszh** [comment]
Failing test is fixed in #236. Please rebase and document your change README. Thanks!

**Comment by xavierog** [comment]
Duly noted; I will proceed with the changes tomorrow evening.

**Comment by xavierog** [comment]
@deniszh: as you can see, I eventually decided to push things a little further: I added ``--time-format`` to whisper-fetch (as a complement to ``--pretty``) then ported both options to whisper-dump. Let me know whether this is still ok.

**Comment by deniszh** [comment]
LGTM
Thanks!

**Pull request merged**
