### PR TITLE
Simple script to find corrupt Whisper files

### PR DESCRIPTION
**Pull request by acdha**
I needed this & figured others might as well

### CODE REVIEW

**Comment by SEJeff** [comment]
Ping, would you be willing to update this code @acdha?

**Comment by acdha** [comment]
@SEJeff Yes, I'll update this tomorrow.

**Comment by acdha** [comment]
I just rebased & added some error handling in https://github.com/graphite-project/whisper/commit/4e2f82b8ad87ee2d544f57ff49130460a1d897d1:

https://github.com/graphite-project/whisper/compare/master...acdha:find-corrupt-whisper-files

A trivial test run looks like this:
```
Deleting corrupt Whisper file: /private/tmp/whisper-tests/test.wsp
Deleting corrupt Whisper file: /private/tmp/whisper-tests/test2.wsp
Deleting corrupt Whisper file: /private/tmp/whisper-tests/read-only/foo.wsp
Unable to delete /private/tmp/whisper-tests/read-only/foo.wsp: [Errno 13] Permission denied: '/private/tmp/whisper-tests/read-only/foo.wsp'
```

**Comment by SEJeff** [comment]
Going forward, stuff like this really should go into @jssjr's [carbonate](https://github.com/jssjr/carbonate) aka whisper-util, but this is clean enough and very useful.

Thanks!

**Pull request merged**
