### PR TITLE
Pep8 2

### PR DESCRIPTION
**Pull request by blackduckx**
Hello,

Following your comments, you will find here the branch without the indentation change (Sorry about that again, I was pretty sure it was a dumb thing to do).

I'll jump to the tox automation  just after.

### CODE REVIEW

**Comment by mleinart** [comment]
I'm okay with this, :+1: 

Will wait for another committer to comment or merge themselves before touching it myself though

Thanks for the work :)

**Comment by blackduckx** [comment]
Thx for the nice feedback.

I am really enjoying carbon/whisper + grafana those days, as it went pretty helpful at my work.
I hope I can help further more in the near future.

**Comment by blackduckx** [comment]
Hello, 

A little up on this merge request  ...

**Comment by drawks** [comment]
thanks

**Pull request merged**
