### PR TITLE
whisper.py: numpy alternative for unpack

### PR DESCRIPTION
**Pull request by gcoudu**
Updated patch with @deniszh comments.

### CODE REVIEW

**Comment by deniszh** [comment]
LGTM! :+1: 
Now tests are green.
But what other respected members of team thinking? 
@SEJeff  @obfuscurity @brutasse ?
Not directly affect Graphite IMO but could be useful for other whisper-based daemons and completely optional now.

**Comment by drawks** [comment]
I've always been a fan of the idea of having some optional dependencies that provide more optimized performance. Numpy as a bolt on to supercharger whisper sounds great to me as long as the test coverage provides some assurance that both code paths provide functionally identical results.

**Comment by deniszh** [comment]
Thanks, @drawks, I'll try to create test. Or maybe @gcoudu can help too. :)

**Comment by gcoudu** [comment]
Sure, let me know how I can help.

**Comment by deniszh** [comment]
Not sure do we need to bring whole Numpy thingy to TravisCI. 
Or maybe some standalone test, which will make some standard writes / numpy reads and vice versa will be enough to merge this? What do you think, @drawks ?

**Comment by DanCech** [comment]
From the looks of things we'd want to have tox envs with and without numpy to test this properly, which would mean we could do away with the `asNumpy` parameter

**Pull request closed without merging**
