### PR TITLE
use whisper-resize if whisper-resize.py is not available

### PR DESCRIPTION
**Pull request by eserte**
The Debian package installs whisper-resize.py without the extension.

### CODE REVIEW

**Comment by deniszh** [comment]
Looks like edge case, but maybe worth merging. @AlexAkulov, what do you think ?

**Comment by eserte** [comment]
I wouldn't say that Debian (this means also: Ubuntu, Mint ...) is an edge case — I would say that's 50% of the Linux server market...

**Comment by deniszh** [comment]
`ln -s /usr/bin/whisper-resize /usr/bin/whisper-resize.py` ? :)

**Comment by deniszh** [comment]
PS: Sorry for mentioning @AlexAkulov - he's not original author of whisper-auto-resize.py, it was @draco2003 
Merged already anyway. :)

**Pull request merged**
