### PR TITLE
whisper-lastupdate: add utility

### PR DESCRIPTION
**Pull request by pabigot**
This provides whisper with a capability similar to "rrdtool lastupdate": it returns the timestamp and value of the last metric added to the database.  The utility can be used by a monitoring system to determine whether updates are still being received.

(I realize the search is potentially inefficient if, in fact, the database is not fairly current.  However this implementation intentionally has minimal impact on the existing implementation.  whisper would need some refactoring in both implementation and architecture to get something better.)

### CODE REVIEW

**Comment by SEJeff** [comment]
Ping @pabigot, will you be willing to refactor this to use python best practices?

Also, perhaps it makes sense to simply modify `whisper-fetch.py` with a `--lastupdate` argument instead of adding an entirely new utility?

**Comment by pabigot** [comment]
@SEJeff  Sorry, no.  I haven't used whisper since shortly after I submitted this, so wouldn't be able to test that it still works after rebasing and refactoring.  Feel free to refactor/reimplement/deal with it as you wish.

**Comment by deniszh** [comment]
Any objections to closing this?

**Comment by pabigot** [comment]
@deniszh no.

**Pull request closed without merging**
