### PR TITLE
Add whisper-fill.py to .travis.yml (0.9.x)

### PR DESCRIPTION
**Pull request by steve-dave**

### CODE REVIEW

**Comment by steve-dave** [comment]
@SEJeff is this one OK too?

**Comment by steve-dave** [comment]
Ping @SEJeff

**Comment by steve-dave** [comment]
ping @SEJeff

**Comment by SEJeff** [comment]
Thanks for being so patient @steve-dave, I suck at having much free time except for when I'm at tech conferences apparently.

**Comment by steve-dave** [comment]
@SEJeff  No worries, life takes over...

**Pull request merged**
