### PR TITLE
Whisper-sync: now accepting an interval

### PR DESCRIPTION
**Pull request by alexandreboisvert**
This pull requests replaces #28. The changes are now incorporated into whisper.py. The new arguments are optional, this should not break the original whisper.merge() behavior.

Testing, comments and feedback are welcome.

### CODE REVIEW

**Comment by deniszh** [comment]
Completely missed that change. Looks like not only good addition to whisper-sync, but probably fix for https://github.com/graphite-project/whisper/issues/163

**Comment by deniszh** [comment]
Ah, disregard that, it will not fix #163. But good anyway. :)

**Comment by alexandreboisvert** [comment]
Thank you for the review. Hope this code will be useful.

**Comment by deniszh** [comment]
Any objections to merging?

**Comment by alexandreboisvert** [comment]
No objections from my side. I see that all checks have passed (green light from travis-ci).

**Comment by deniszh** [comment]
Merging

**Pull request merged**
