### PR TITLE
Switch to setuptools

### PR DESCRIPTION
**Pull request by piotr1212**
removes warnings
UserWarning: Unknown distribution option: 'install_requires'
UserWarning: Unknown distribution option: 'long_description_content_type'

setuptools seems to be the recommended way now.

### CODE REVIEW

**Comment by deniszh** [comment]
👍 
Question - what we going to do with carbon and gtaphite-web?
I mean, now we use this - https://github.com/graphite-project/carbon/blob/master/setup.py#L53-L58

**Comment by deniszh** [comment]
We can also revert that pesky `GRAPHITE_NO_PREFIX=True` logic too... not directly related, though.

**Comment by piotr1212** [comment]
see https://github.com/graphite-project/carbon/pull/835

**Comment by piotr1212** [comment]
This one can already be merged, still writing docs and testing for carbon and web.

**Pull request merged**
