### PR TITLE
support for 'avg_zero' aggregation

### PR DESCRIPTION
**Pull request by penpen**
Hi!
There is support for average aggregation which treats null values as zero, since for avg traffic/bandwidth
values, ignoring 'null' values makes hourly/daily traffic calculations wrong (hitcount(metric, "1d", true) for example).

### CODE REVIEW

**Comment by penpen** [comment]
@SEJeff 
Hi, I changed files according your comments.

**Comment by SEJeff** [comment]
@penpen: can you rebase this against master once more? Then I'll merge it. Thanks!

**Comment by penpen** [comment]
@SEJeff merged.

**Comment by SEJeff** [comment]
Thanks for your contribution @penpen, it is much appreciated!

**Pull request merged**
