### PR TITLE
.gitignore intellij project files

### PR DESCRIPTION
**Pull request by ryan-williams**

### CODE REVIEW

**Comment by SEJeff** [comment]
Not sure why you'd use a Java editor for Python, but to eat their own! I'm a hardcore vim guy myself.

**Comment by deniszh** [comment]
Pycharm is quite nice, I'm also using it. But I'm usually just add .idea to
.git/info/exclude after cloning.
za 10 jan. 2015 в 12:58, Jeff Schroeder <notifications@github.com>:

**Comment by SEJeff** [comment]
@deniszh Feel free to open a PR adding that to the `.gitignore`. We're always open to PRs that make it more pleasant to hack on graphite bits within reason.

**Comment by deniszh** [comment]
Pycharm is just limited version of IntelliJ IDEA, so, it's covered up by
this commit too. :)
Just my 2 cents...
za 10 jan. 2015 в 21:03, Jeff Schroeder <notifications@github.com>:

**Comment by brutasse** [comment]
A global `~/.gitignore` is useful for that kind of thing :)

**Comment by ryan-williams** [comment]
sorry, late to this thread! I shelled out for the pro version of intellij a few years ago partly because it supposedly incorporated the PyCharm functionality (or rather: PyCharm is logically the IntelliJ python plugin, forked out as a demo to aid in their freemium-upsell pitch), so yea, IntelliJ can actually be a reasonable python editor, but it makes sense that that was confusing at first look :)

It seems like JetBrains has doubled down on this approach with other ~"standalone" IDEs like [WebStorm](https://www.jetbrains.com/webstorm/); frustratingly, they seem to have departed from the model of unifying the best of all things in the paid version of IntelliJ in favor of being able to charge for multiple IDEs per developer, because I've run into web-dev deficiencies in IntelliJ that I'm told are fixed or improved upon in WebStorm.

anyway, thanks for merging!

**Pull request merged**
